### ISSUE TITLE
high_resolution_clock and steady_clock mismatch

### ISSUE THREAD

**Issue by tigrazone** [IwakuraRein/CIS-565-Final-VR-Raytracer#2]
When I compile restir_direct branch with MinGW GCC, I have error.
Changes 
src/sample_example.cpp
line 400
`m_rtxState.time = (uint)(std::chrono::duration<double>(std::chrono::high_resolution_clock::now() - m_start_time).count() * 1000.0);`
to 
`m_rtxState.time = (uint)(std::chrono::duration<double>(std::chrono::steady_clock::now() - m_start_time).count() * 1000.0);`
and line 89 from 
`m_start_time = std::chrono::high_resolution_clock::now();`
to 
`m_start_time = std::chrono::steady_clock::now();`
fix this problem.

After this changes Visual Studio also compile projects ok.
Change high_resolution_clock::now() to steady_clock::now() is a Vusual Studio alias

**Comment by IwakuraRein** [comment]
Thanks for your feedback! This project is in progress so you may come back and take a look occasionally. We are looking forward to hearing more suggestions from you.

**Comment by tigrazone** [comment]
lets communicate via twitter or so. I message you to twitter
